---

- name: install the php ppa
  apt_repository: >
    repo={{ php_ppa }}
    state=present
    update_cache=yes

- name: Install php package
  apt: pkg={{ item }} state=present
  with_items: php_packages

- name: put the config in place
  template: src=php.ini.j2 dest=/etc/php5/fpm/conf.d/user.ini
  notify: restart fpm

- name: start fpm service
  service: name=php5-fpm state=started enabled=yes
  notify: reload nginx
